#!/bin/bash
#SBATCH -J init
#SBATCH -n 1 -N 1
##SBATCH -t 24:00:00
#SBATCH -t 4-24:00:00
#SBATCH -p long
#SBATCH --constraint=ib
#SBATCH -o %A.out
#SBATCH -e %A.err

start=$SECONDS

module purge
module load python/3.8.1
source /work/props/Rob/software/hoomd3.1-mod/hoomdmod-venv/bin/activate
module load gcc/11.1.0
module load openmpi/4.1.2-gcc11.1
python3 sim-init.py

time=$((SECONDS-start))
echo The simulation ran for $((time / 86400))day"(s)" $(((time / 3600) % 24))hr"(s)" $(((time / 60) % 60))min $((time % 60))sec real "(wall clock)" time >&1

#seff $SLURM_JOBID
