#!/bin/bash
#SBATCH -J anlyz
#SBATCH -n 1 -N 1
#SBATCH -t 1:00:00
#SBATCH -o %A-anlyz.out
#SBATCH -e %A-anlyz.err

# source into the virtual environment
module load python/3.8.1
source /work/props/Rob/software/hoomd3.1-mod/hoomdmod-venv/bin/activate
module load gcc/11.1.0
module load openmpi/4.1.2-gcc11.1

# run the analysis file
python sim-eq-analysis.py

