#!/bin/bash

#SBATCH -J BItopo
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH -t 24:00:00
##SBATCH -t 4-24:00:00
##SBATCH -p long
#SBATCH --mem=128Gb
#SBATCH -o %A-ebc.out
#SBATCH -e %A-ebc.err

start=$SECONDS

module load miniconda3/24.11.1
source /projects/props/Rob/software/hoomd4.2.1-modgpu/hoomdmodgpu4.2.1-venv/bin/activate
module load OpenMPI/4.1.6

# analyze topology of the network
python sim-analyze-topology.py

# basic stats about each bimodal/monomodal composition
python sim-analyze-composition.py

# save network data for quench and visualization
python sim-batch-make-psf-types.py
python sim-batch-cluster-colored-gsds.py

time=$((SECONDS-start))
echo The simulation ran for $((time / 86400))day"(s)" $(((time / 3600) % 24))hr"(s)" $(((time / 60) % 60))min $((time % 60))sec real "(wall clock)" time >&1
